version: '3.5'

services:
    db-boilerplate:
        container_name: db-boilerplate
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
            PGDATA: /data/postgres
        volumes:
            - db-boilerplate:/data/postgres
        ports:
            - '7151:5432'
        networks:
            - ms-gateway_databases

networks:
    ms-gateway_databases:
        external: true

volumes:
    db-boilerplate:
